services:
  kilo-agents:
    container_name: kilo-agents
    build: .
    user: 1000:1000
    volumes:
      - ./workspace:/workspace
      - ./.codex:/data/.codex
      - ./.kilocode:/.kilocode
      - ./.gitconfig:/.gitconfig
      - ./data:/data
    env_file:
      - .env
    restart: unless-stopped
